apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kadalu-csi-provisioner
  namespace: kadalu
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: kadalu-csi-provisioner
      app.kubernetes.io/part-of: kadalu
  serviceName: kadalu-csi-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: kadalu-csi-provisioner
        app.kubernetes.io/part-of: kadalu
      name: csi-provisioner
      namespace: kadalu
    spec:
      hostAliases:
      - ip: "192.168.10.11"
        hostnames:
        - "master01.gluster.local"
      - ip: "192.168.10.12"
        hostnames:
        - "node01.gluster.local"
      - ip: "192.168.10.13"
        hostnames:
        - "node02.gluster.local"
      - ip: "192.168.10.14"
        hostnames:
        - "node03.gluster.local"
      containers:
      - args:
        - --csi-address=$(ADDRESS)
        - --timeout=3m
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        image: docker.io/raspbernetes/csi-external-provisioner:2.0.2
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        image: docker.io/raspbernetes/csi-external-attacher:3.0.0
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      - env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: SECRET_GLUSTERQUOTA_SSH_USERNAME
          valueFrom:
            secretKeyRef:
              key: glusterquota-ssh-username
              name: glusterquota-ssh-secret
              optional: true
        - name: CSI_ENDPOINT
          value: unix://plugin/csi.sock
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        - name: CSI_ROLE
          value: provisioner
        image: docker.io/kadalu/kadalu-csi:1.3.0
        imagePullPolicy: IfNotPresent
        name: kadalu-provisioner
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - CAP_SYS_ADMIN
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugin
          name: socket-dir
        - mountPath: /var/lib/gluster
          name: glusterfsd-volfilesdir
        - mountPath: /dev
          name: gluster-dev
        - mountPath: /var/log/gluster
          name: varlog
        - mountPath: /etc/secret-volume
          name: secret-volume
          readOnly: true
      - args:
        - -c
        - while true; do logcnt=$(/bin/ls /var/log/gluster/ | wc -l); if [ ${logcnt}
          -gt 0 ]; then break; fi; sleep 5; done; tail -F /var/log/gluster/*.log
        command:
        - /bin/sh
        image: docker.io/library/busybox
        imagePullPolicy: IfNotPresent
        name: kadalu-logging
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/gluster
          name: varlog
      - args:
        - --csi-address=$(ADDRESS)
        - --timeout=3m
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        image: docker.io/raspbernetes/csi-external-resizer:1.0.0
        imagePullPolicy: IfNotPresent
        name: csi-resizer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kadalu-csi-provisioner
      serviceAccountName: kadalu-csi-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: socket-dir
      - configMap:
          defaultMode: 420
          name: kadalu-info
        name: glusterfsd-volfilesdir
      - hostPath:
          path: /dev
          type: ""
        name: gluster-dev
      - emptyDir: {}
        name: varlog
      - name: secret-volume
        secret:
          defaultMode: 384
          optional: true
          secretName: glusterquota-ssh-secret
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
