apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"csi-driver","app.kubernetes.io/name":"kadalu-csi-nodeplugin","app.kubernetes.io/part-of":"kadalu"},"name":"kadalu-csi-nodeplugin","namespace":"kadalu"},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/component":"csi-driver","app.kubernetes.io/name":"kadalu-csi-nodeplugin","app.kubernetes.io/part-of":"kadalu"}},"template":{"metadata":{"labels":{"app.kubernetes.io/component":"csi-driver","app.kubernetes.io/name":"kadalu-csi-nodeplugin","app.kubernetes.io/part-of":"kadalu"},"namespace":"kadalu"},"spec":{"containers":[{"args":["--v=5","--csi-address=$(ADDRESS)","--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"],"env":[{"name":"ADDRESS","value":"/plugin/csi.sock"},{"name":"DRIVER_REG_SOCK_PATH","value":"/var/lib/kubelet/plugins/kadalu/csi.sock"},{"name":"KUBE_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"KADALU_VERSION","value":"1.3.0"},{"name":"K8S_DIST","value":"kubernetes"},{"name":"VERBOSE","value":"no"}],"image":"docker.io/raspbernetes/csi-node-driver-registrar:2.0.1","lifecycle":{"preStop":{"exec":{"command":["/bin/sh","-c","rm -rf /registration/kadalu /registration/kadalu-reg.sock"]}}},"name":"csi-node-driver-registrar","volumeMounts":[{"mountPath":"/plugin","name":"plugin-dir"},{"mountPath":"/registration","name":"registration-dir"}]},{"env":[{"name":"NODE_ID","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"CSI_ENDPOINT","value":"unix://plugin/csi.sock"},{"name":"KADALU_VERSION","value":"1.3.0"},{"name":"K8S_DIST","value":"kubernetes"},{"name":"VERBOSE","value":"no"},{"name":"CSI_ROLE","value":"nodeplugin"}],"image":"docker.io/kadalu/kadalu-csi:1.3.0","lifecycle":{"postStart":{"exec":{"command":["/bin/sh","-c","mount | grep glusterfs | awk '{print $1 \" \" $3}' | sed 's/:/ /' | awk '{print \"umount \" $3 \";glusterfs --process-name fuse --volfile-id \" $2 \" --volfile-server \" $1 \" --log-level=WARNING \" $3}' > /tmp/remount.sh ; chmod +x /tmp/remount.sh ; /tmp/remount.sh\n"]}}},"name":"kadalu-nodeplugin","securityContext":{"allowPrivilegeEscalation":true,"capabilities":{"add":["SYS_ADMIN"]},"privileged":true},"volumeMounts":[{"mountPath":"/plugin","name":"plugin-dir"},{"mountPath":"/var/lib/kubelet/pods","mountPropagation":"Bidirectional","name":"pods-mount-dir"},{"mountPath":"/var/lib/gluster","name":"glusterfsd-volfilesdir"},{"mountPath":"/dev","name":"gluster-dev"},{"mountPath":"/var/log/gluster","name":"varlog"},{"mountPath":"/var/lib/kubelet/plugins/kubernetes.io/csi","mountPropagation":"Bidirectional","name":"csi-dir"}]},{"args":["-c","while true; do logcnt=$(/bin/ls /var/log/gluster/ | wc -l); if [ ${logcnt} -gt 0 ]; then break; fi; sleep 5; done; tail -f /var/log/gluster/*.log"],"command":["/bin/sh"],"image":"docker.io/library/busybox","imagePullPolicy":"IfNotPresent","name":"kadalu-logging","volumeMounts":[{"mountPath":"/var/log/gluster","name":"varlog"}]}],"serviceAccountName":"kadalu-csi-nodeplugin","volumes":[{"hostPath":{"path":"/var/lib/kubelet/plugins/kadalu","type":"DirectoryOrCreate"},"name":"plugin-dir"},{"hostPath":{"path":"/var/lib/kubelet/pods","type":"Directory"},"name":"pods-mount-dir"},{"hostPath":{"path":"/var/lib/kubelet/plugins_registry/","type":"Directory"},"name":"registration-dir"},{"configMap":{"name":"kadalu-info"},"name":"glusterfsd-volfilesdir"},{"hostPath":{"path":"/dev"},"name":"gluster-dev"},{"emptyDir":{},"name":"varlog"},{"hostPath":{"path":"/var/lib/kubelet/plugins/kubernetes.io/csi/","type":"DirectoryOrCreate"},"name":"csi-dir"}]}},"updateStrategy":{"type":"OnDelete"}}}
  creationTimestamp: "2025-08-04T12:49:12Z"
  generation: 1
  labels:
    app.kubernetes.io/component: csi-driver
    app.kubernetes.io/name: kadalu-csi-nodeplugin
    app.kubernetes.io/part-of: kadalu
  name: kadalu-csi-nodeplugin
  namespace: kadalu
  resourceVersion: "1782677"
  uid: c60d48e8-f24f-4635-b859-ba3ed9afd4b3
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: csi-driver
      app.kubernetes.io/name: kadalu-csi-nodeplugin
      app.kubernetes.io/part-of: kadalu
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: csi-driver
        app.kubernetes.io/name: kadalu-csi-nodeplugin
        app.kubernetes.io/part-of: kadalu
      namespace: kadalu
    spec:
      hostAliases:
      - ip: "10.10.129.15"
        hostnames:
        - "master01.gluster.local"
      - ip: "10.10.129.16"
        hostnames:
        - "node01.gluster.local"
      - ip: "10.10.129.17"
        hostnames:
        - "node02.gluster.local"
      - ip: "10.10.129.18"
        hostnames:
        - "node03.gluster.local"
      containers:
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: /plugin/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/kadalu/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        image: docker.io/raspbernetes/csi-node-driver-registrar:2.0.1
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/kadalu /registration/kadalu-reg.sock
        name: csi-node-driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugin
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix://plugin/csi.sock
        - name: KADALU_VERSION
          value: 1.3.0
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        - name: CSI_ROLE
          value: nodeplugin
        image: docker.io/kadalu/kadalu-csi:1.3.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - |
                mount | grep glusterfs | awk '{print $1 " " $3}' | sed 's/:/ /' | awk '{print "umount " $3 ";glusterfs --process-name fuse --volfile-id " $2 " --volfile-server " $1 " --log-level=WARNING " $3}' > /tmp/remount.sh ; chmod +x /tmp/remount.sh ; /tmp/remount.sh
        name: kadalu-nodeplugin
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /plugin
          name: plugin-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: pods-mount-dir
        - mountPath: /var/lib/gluster
          name: glusterfsd-volfilesdir
        - mountPath: /dev
          name: gluster-dev
        - mountPath: /var/log/gluster
          name: varlog
        - mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
          mountPropagation: Bidirectional
          name: csi-dir
      - args:
        - -c
        - while true; do logcnt=$(/bin/ls /var/log/gluster/ | wc -l); if [ ${logcnt}
          -gt 0 ]; then break; fi; sleep 5; done; tail -f /var/log/gluster/*.log
        command:
        - /bin/sh
        image: docker.io/library/busybox
        imagePullPolicy: IfNotPresent
        name: kadalu-logging
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/gluster
          name: varlog
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kadalu-csi-nodeplugin
      serviceAccountName: kadalu-csi-nodeplugin
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/kadalu
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
        name: pods-mount-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: Directory
        name: registration-dir
      - configMap:
          defaultMode: 420
          name: kadalu-info
        name: glusterfsd-volfilesdir
      - hostPath:
          path: /dev
          type: ""
        name: gluster-dev
      - emptyDir: {}
        name: varlog
      - hostPath:
          path: /var/lib/kubelet/plugins/kubernetes.io/csi/
          type: DirectoryOrCreate
        name: csi-dir
  updateStrategy:
    type: OnDelete
status:
  currentNumberScheduled: 4
  desiredNumberScheduled: 4
  numberAvailable: 4
  numberMisscheduled: 0
  numberReady: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
