apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2025-08-04T12:49:02Z","generation":1,"labels":{"app.kubernetes.io/component":"operator","app.kubernetes.io/name":"kadalu-operator","app.kubernetes.io/part-of":"kadalu"},"name":"operator","namespace":"kadalu","resourceVersion":"1782429","uid":"25d9f71a-180c-458e-8bbe-6894dfb27d8b"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"name":"kadalu"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"prometheus.io/port":"8050","prometheus.io/scrape":"true"},"creationTimestamp":null,"labels":{"app.kubernetes.io/part-of":"kadalu","name":"kadalu"}},"spec":{"containers":[{"env":[{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"kadalu-operator"},{"name":"IMAGES_HUB","value":"docker.io"},{"name":"DOCKER_USER","value":"kadalu"},{"name":"KADALU_VERSION","value":"1.3.0"},{"name":"KADALU_NAMESPACE","value":"kadalu"},{"name":"KUBELET_DIR","value":"/var/lib/kubelet"},{"name":"K8S_DIST","value":"kubernetes"},{"name":"VERBOSE","value":"no"}],"image":"docker.io/kadalu/kadalu-operator:1.3.0","imagePullPolicy":"IfNotPresent","name":"kadalu-operator","resources":{},"securityContext":{"capabilities":{},"privileged":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","hostAliases":[{"hostnames":["master01.gluster.local"],"ip":"10.10.129.15"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"kadalu-operator","serviceAccountName":"kadalu-operator","terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2025-08-04T12:49:12Z","lastUpdateTime":"2025-08-04T12:49:12Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2025-08-04T12:49:02Z","lastUpdateTime":"2025-08-04T13:22:14Z","message":"ReplicaSet \"operator-786fbbc469\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-08-04T12:49:02Z"
  generation: 2
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: kadalu-operator
    app.kubernetes.io/part-of: kadalu
  name: operator
  namespace: kadalu
  resourceVersion: "1790678"
  uid: 25d9f71a-180c-458e-8bbe-6894dfb27d8b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: kadalu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "8050"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: kadalu
        name: kadalu
    spec:
      containers:
      - env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: kadalu-operator
        - name: IMAGES_HUB
          value: docker.io
        - name: DOCKER_USER
          value: kadalu
        - name: KADALU_VERSION
          value: 1.3.0
        - name: KADALU_NAMESPACE
          value: kadalu
        - name: KUBELET_DIR
          value: /var/lib/kubelet
        - name: K8S_DIST
          value: kubernetes
        - name: VERBOSE
          value: "no"
        image: docker.io/kadalu/kadalu-operator:1.3.0
        imagePullPolicy: IfNotPresent
        name: kadalu-operator
        resources: {}
        securityContext:
          capabilities: {}
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      hostAliases:
      - ip: "10.10.129.15"
        hostnames:
        - "master01.gluster.local"
      - ip: "10.10.129.16"
        hostnames:
        - "node01.gluster.local"
      - ip: "10.10.129.17"
        hostnames:
        - "node02.gluster.local"
      - ip: "10.10.129.18"
        hostnames:
        - "node03.gluster.local"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kadalu-operator
      serviceAccountName: kadalu-operator
      terminationGracePeriodSeconds: 30
