apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gluster-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: kadalu.external-storage # <--- CHANGE THIS LINE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gluster-pv
          mountPath: /usr/share/nginx/html
        command: ["/bin/sh"]
        args: ["-c", "echo 'Hello from GlusterFS!' > /usr/share/nginx/html/index.html && while true; do sleep 30; done;"]
      volumes:
      - name: gluster-pv
        persistentVolumeClaim:
          claimName: gluster-pvc
