---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-csi-thin-pv
spec:
  storageClassName: glusterfs-csi-arbiter
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
