---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-csi-arbiter
provisioner: org.gluster.glusterfs
parameters:
  replicas: "2"
  arbiterType: "thin"
  arbiterPath: "192.168.10.90:/mnt/arbiter-path:24007"
