---
apiVersion: v1
kind: Pod
metadata:
  name: ta-redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/mnt/gluster"
          name: glustervirtblockcsivol
  volumes:
    - name: glustervirtblockcsivol
      persistentVolumeClaim:
        claimName: glustervirtblock-csi-thin-pv
