---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glustervirtblock-csi-thin-arbiter
provisioner: org.gluster.glustervirtblock
parameters:
  replicas: "2"
  arbiterType: "thin"
  arbiterPath: "192.168.122.121:/mnt/arbiter-path:24007"
