---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glustervirtblock-csi-thin-pv
spec:
  storageClassName: glustervirtblock-csi-thin-arbiter
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
